postgres.driver=org.postgresql.Driver
postgres.url=jdbc:postgresql://localhost:5432/myfirstdb
postgres.name=postgres
postgres.password=postgres

# Fallback ??? H2 (???????????????)
# postgres.driver=org.h2.Driver
# postgres.url=jdbc:h2:mem:myfirstdb;DB_CLOSE_DELAY=-1
# postgres.name=sa
# postgres.password=